### ISSUE TITLE
Transient failure on KafkaConsumerTest.testStartConsumersNoCommit

### ISSUE THREAD

**Issue by gianm** [druid-io/tranquility#102]
https://travis-ci.org/druid-io/tranquility/builds/103996525

```
[error] Test com.metamx.tranquility.kafka.KafkaConsumerTest.testStartConsumersNoCommit failed: org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds, took 60.003 sec
[error]     at sun.misc.Unsafe.park(Native Method)
[error]     at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[error]     at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
[error]     at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
[error]     at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
[error]     at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
[error]     at com.metamx.tranquility.kafka.KafkaConsumerTest.testStartConsumersNoCommit(KafkaConsumerTest.java:220)
[error]     ...
```

**Comment by gianm** [comment]
observed in #101

**Comment by dclim** [comment]
I believe the issue is that the Kafka producer starts pushing messages before the broker is up so the counter doesn't decrement to 0 and it blocks until it times out. I tried to fix it by writing a message to a warm-up topic before starting the real test.. maybe it would help to increase the number of messages written as warm up.

**Comment by gianm** [comment]
@dclim hmm, I don't think that should be a problem, since the producer should wait for the broker to come up and then send the message. At least that's how the kafka producer is supposed to work, it shouldn't return OK from `get()` unless the message went through.

In #105 I'm gonna try setting `auto.offset.reset` to `smallest` (default is `largest`). Possibly what was going on with the failures is that the consumer was a bit slow to start up, and when it started reading at the end of the topic, it missed some messages.

**Comment by dclim** [comment]
Yeah I thought the get() call would be blocking. Setting the auto.offset.reset to smallest sounds like a good thing to try out. Thanks Gian.
