### ISSUE TITLE
tranquility-kafka does not work with 0.8.x brokers

### ISSUE THREAD

**Issue by gianm** [druid-io/tranquility#108]
see https://issues.apache.org/jira/browse/KAFKA-2845

So I think we need to downgrade our kafka lib to work with 0.8.x brokers. It sounds like the older kafka client should work with both 0.8.x and 0.9.x brokers.

**Comment by gianm** [comment]
specifically, you get a BufferUnderflowException when the client tries to talk to the broker.

**Comment by DanisHack** [comment]
Is this fixed ? I got BufferUnderflowException as well

**Comment by gianm** [comment]
@DanisHack not yet, expect a fix in the next version. You could probably get the existing version to work by replacing the kafka 0.9.0.0 jar with a kafka 0.8.2.2 jar but I have not tested that.
