### ISSUE TITLE
[tranquility-spark] lazy val makeBeam creates a new ZK connection for each RDD of a StreamingContext

### ISSUE THREAD

**Issue by plelevier** [druid-io/tranquility#114]
Hello,

I'm trying to figure out how to use in a good way tranquility in a Spark Streaming Context.

In the [Tranquility Spark Documentation](https://github.com/druid-io/tranquility/blob/master/docs/spark.md), nothing is said regarding the batchDuration of the Spark Streaming Context.

I'd like to know if there a good practice about that batchDuration, ie : should we have that duration smaller/higher than the segmentGranularity(+ windowPeriod?) or the queryGranularity ?

From what I understand, it should not be correlated (thinking about avoiding too much data loss/duplication in case of a failure of a task), but I'd like to get some confirmation about that.

It brings me to the recommended and documented pattern for creating a `BeamFactory` (ie, `makeBeam` as a `lazy val`), in a StreamingContext : 
- The BeamFactory instance is created on the SparkDriver
- It is then serialized and sent to the Spark Executors

Then, **for each partition of each RDD** :
- That BeamFactory is deserialized 
- The `BeamFactory.makeBeam` creates a new Curator/Zookeeper Connection (I was not sure about that, thinking each RDD of a given executor were sharing the same deserialized object, but adding a log line in the `lazy val makeBeam = { ... }` shows that the method is executed for each partition for each new RDD)

Now, given a batchDuration of 1 second and some events filling 4 partitions, we'll get 4 **new** Curator/Zookeeper connections each second : 
- Is that the desired behavior?
- If yes, are these Curator/Zookeeper client closed properly by the tranquilizer? (According to the `curator.close()` call in the [Scala example](https://github.com/druid-io/tranquility/blob/master/core/src/test/scala/com/metamx/tranquility/example/ScalaExample.scala), it is the user's responsability to close the curator. How to do that using the lazy val pattern?). And then, why asking for the user to start the curator using a lazy, when it may be better to start it in the foreachPartition of the `BeamRDD.propagate`method and close it properly at the end?
- If no, it seems we got an issue here. I'm thinking about writing an CuratorPool object to avoid this problem. (not sure that it will work)

For the record, here is some spark executor logs (with 2 batches, given batchDuration = 10 seconds), showing the problem (each RDD is empty).

Please take a look to the "EventBeamFactory: Make Beam" and "EventBeamFactory: Start Curator" messages, which are logs added respectively at the very start of the `lazy val makeBeam` initialization and just before the `curator.start()` call.

After a while, we're getting a `too many connection` error on Zookeeper

```
16/02/05 11:41:30 INFO CoarseGrainedExecutorBackend: Got assigned task 41
16/02/05 11:41:30 INFO Executor: Running task 1.0 in stage 10.0 (TID 41)
16/02/05 11:41:30 INFO TorrentBroadcast: Started reading broadcast variable 10
16/02/05 11:41:30 INFO MemoryStore: Block broadcast_10_piece0 stored as bytes in memory (estimated size 2.7 KB, free 33.7 KB)
16/02/05 11:41:30 INFO TorrentBroadcast: Reading broadcast variable 10 took 73 ms
16/02/05 11:41:30 INFO MemoryStore: Block broadcast_10 stored as values in memory (estimated size 5.0 KB, free 38.7 KB)
16/02/05 11:41:30 INFO KafkaRDD: Beginning offset 0 is the same as ending offset skipping example-topic1 0
16/02/05 11:41:30 INFO EventBeamFactory: Make Beam
16/02/05 11:41:30 INFO EventBeamFactory: Start Curator
16/02/05 11:41:30 INFO CuratorFrameworkImpl: Starting
16/02/05 11:41:30 INFO ZooKeeper: Initiating client connection, connectString=zookeeper:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@2752d6ff
16/02/05 11:41:30 INFO ClientCnxn: Opening socket connection to server zookeeper_1/172.17.0.6:2181. Will not attempt to authenticate using SASL (unknown error)
16/02/05 11:41:30 INFO ClientCnxn: Socket connection established to zookeeper_1/172.17.0.6:2181, initiating session
16/02/05 11:41:30 INFO ClientCnxn: Session establishment complete on server zookeeper_1/172.17.0.6:2181, sessionid = 0x152b0a3979807d1, negotiated timeout = 40000
16/02/05 11:41:30 INFO ConnectionStateManager: State change: CONNECTED
16/02/05 11:41:30 INFO LoggingEmitter: Start: started [true]
16/02/05 11:41:30 INFO Executor: Finished task 1.0 in stage 10.0 (TID 41). 875 bytes result sent to driver
16/02/05 11:41:30 INFO CoarseGrainedExecutorBackend: Got assigned task 42
16/02/05 11:41:30 INFO Executor: Running task 2.0 in stage 10.0 (TID 42)
16/02/05 11:41:30 INFO KafkaRDD: Beginning offset 0 is the same as ending offset skipping example-topic2 0
16/02/05 11:41:30 INFO EventBeamFactory: Make Beam
16/02/05 11:41:30 INFO EventBeamFactory: Start Curator
16/02/05 11:41:30 INFO CuratorFrameworkImpl: Starting
16/02/05 11:41:30 INFO ZooKeeper: Initiating client connection, connectString=zookeeper:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@77b39141
16/02/05 11:41:30 INFO ClientCnxn: Opening socket connection to server zookeeper_1/172.17.0.6:2181. Will not attempt to authenticate using SASL (unknown error)
16/02/05 11:41:30 INFO ClientCnxn: Socket connection established to zookeeper_1/172.17.0.6:2181, initiating session
16/02/05 11:41:30 INFO LoggingEmitter: Start: started [true]
16/02/05 11:41:30 INFO ClientCnxn: Session establishment complete on server zookeeper_1/172.17.0.6:2181, sessionid = 0x152b0a3979807d3, negotiated timeout = 40000
16/02/05 11:41:30 INFO ConnectionStateManager: State change: CONNECTED
16/02/05 11:41:30 INFO Executor: Finished task 2.0 in stage 10.0 (TID 42). 875 bytes result sent to driver
16/02/05 11:41:30 INFO BlockManager: Removing RDD 29
16/02/05 11:41:30 INFO BlockManager: Removing RDD 28
16/02/05 11:41:30 INFO BlockManager: Removing RDD 27
16/02/05 11:41:40 INFO CoarseGrainedExecutorBackend: Got assigned task 45
16/02/05 11:41:40 INFO Executor: Running task 1.0 in stage 11.0 (TID 45)
16/02/05 11:41:40 INFO TorrentBroadcast: Started reading broadcast variable 11
16/02/05 11:41:40 INFO MemoryStore: Block broadcast_11_piece0 stored as bytes in memory (estimated size 2.7 KB, free 41.4 KB)
16/02/05 11:41:40 INFO TorrentBroadcast: Reading broadcast variable 11 took 96 ms
16/02/05 11:41:40 INFO MemoryStore: Block broadcast_11 stored as values in memory (estimated size 5.0 KB, free 46.4 KB)
16/02/05 11:41:40 INFO KafkaRDD: Beginning offset 0 is the same as ending offset skipping example-topic1 0
16/02/05 11:41:40 INFO EventBeamFactory: Make Beam
16/02/05 11:41:40 INFO EventBeamFactory: Start Curator
16/02/05 11:41:40 INFO CuratorFrameworkImpl: Starting
16/02/05 11:41:40 INFO ZooKeeper: Initiating client connection, connectString=zookeeper:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@364ae98f
16/02/05 11:41:40 INFO ClientCnxn: Opening socket connection to server zookeeper_1/172.17.0.6:2181. Will not attempt to authenticate using SASL (unknown error)
16/02/05 11:41:40 INFO LoggingEmitter: Start: started [true]
16/02/05 11:41:40 INFO ClientCnxn: Socket connection established to zookeeper_1/172.17.0.6:2181, initiating session
16/02/05 11:41:40 INFO ClientCnxn: Session establishment complete on server zookeeper_1/172.17.0.6:2181, sessionid = 0x152b0a3979807d6, negotiated timeout = 40000
16/02/05 11:41:40 INFO ConnectionStateManager: State change: CONNECTED
16/02/05 11:41:40 INFO Executor: Finished task 1.0 in stage 11.0 (TID 45). 875 bytes result sent to driver
16/02/05 11:41:40 INFO CoarseGrainedExecutorBackend: Got assigned task 47
16/02/05 11:41:40 INFO Executor: Running task 3.0 in stage 11.0 (TID 47)
16/02/05 11:41:40 INFO KafkaRDD: Beginning offset 0 is the same as ending offset skipping example-topic2 0
16/02/05 11:41:40 INFO EventBeamFactory: Make Beam
16/02/05 11:41:40 INFO EventBeamFactory: Start Curator
16/02/05 11:41:40 INFO CuratorFrameworkImpl: Starting
16/02/05 11:41:40 INFO ZooKeeper: Initiating client connection, connectString=zookeeper:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@2dd6535a
16/02/05 11:41:40 INFO ClientCnxn: Opening socket connection to server zookeeper_1/172.17.0.6:2181. Will not attempt to authenticate using SASL (unknown error)
16/02/05 11:41:40 INFO LoggingEmitter: Start: started [true]
16/02/05 11:41:40 INFO ClientCnxn: Socket connection established to zookeeper_1/172.17.0.6:2181, initiating session
16/02/05 11:41:40 INFO ClientCnxn: Session establishment complete on server zookeeper_1/172.17.0.6:2181, sessionid = 0x152b0a3979807d8, negotiated timeout = 40000
16/02/05 11:41:40 INFO ConnectionStateManager: State change: CONNECTED
16/02/05 11:41:40 INFO Executor: Finished task 3.0 in stage 11.0 (TID 47). 875 bytes result sent to driver
16/02/05 11:41:40 INFO BlockManager: Removing RDD 32
16/02/05 11:41:40 INFO BlockManager: Removing RDD 31
16/02/05 11:41:41 INFO BlockManager: Removing RDD 30
```

and here is some of the BeamFactory code : 
```scala
class EventBeamFactory extends BeamFactory[Map[String,Any]] {

  @transient lazy val log = Logger.getLogger(getClass.getName)

  lazy val makeBeam: Beam[Map[String,Any]] = {

    log.info("Make Beam")
    val curator = CuratorFrameworkFactory.newClient(
      ...,
      new BoundedExponentialBackoffRetry(100, 3000, 5)
    )
    log.info("Start Curator")
    curator.start()
    
   DruidBreams.builder(...)
      .druidBeamConfig(new DruidBeamConfig(randomizeTaskId=true))
      .curator(curator)
      .discoveryPath(...)
      .location(...)
      .rollup(...)
      .tuning(...)
      .buildBeam()
  }
}

**Comment by gianm** [comment]
@plelevier thanks a lot for raising this issue. I'm not an expert on spark streaming but I will answer as best as I can.

1. I think you're right that the batch duration shouldn't matter too much. For perf reasons you don't want it to be *super* short, because you do have to wait for confirmation at the end of each micro batch, but as long as it's something reasonable then it shouldn't matter exactly what it is. It shouldn't have to be related in any way to the window period, segment granularity, query granularity, etc.

2. I thought that each partition of an RDD would share the BeamFactory too. But it seems like it doesn't. So I think we'll have to adjust how we recommend doing things.

3. The lack of closing is definitely not ideal, although I'm not sure how to close shared resources like this in Spark. Maybe there's some way to hook into the context shutdown? Registering a shutdown hook doesn't seem like the right approach since it would execute concurrently with Spark's own hooks, and we don't want to close the pool before the Spark job shuts down.

**Comment by plelevier** [comment]
@gianm Ok, thanks for your answers!

Actually I found a way to manage this problem, using a singleton object (You can see an example of this pattern in the [spark-kafka-writer repository](https://github.com/cloudera/spark-kafka-writer/blob/master/src/main/scala/org/cloudera/spark/streaming/kafka/ProducerCache.scala) )

I've only tested it using empty RDDs, I still need to check if there is no problem when there is something to propagate

Here is what I did : 

```scala 
object CuratorCache {

  val log = Logger.getLogger(getClass.getName)
  val curators = new scala.collection.concurrent.TrieMap[String, CuratorFramework]()

  // Shutdown hook to close the connections when the executor exits
  sys.addShutdownHook {
    curators.values.foreach { curator =>
      curator.close()
    }
  }

  /**
    *
    * @param curatorId The curator instance id
    * @param connectionString The curator quorum connection string
    * @param retryPolicy The curator retry policy
    * @return A new started curator if none has already been set for the curatorId, otherwise the existing one
    */
  def apply(curatorId: String, connectionString: String, retryPolicy: RetryPolicy): CuratorFramework =
    curators.getOrElseUpdate(curatorId, {
      log.info(s"New curator <$curatorId:$connectionString>")
      val curator = CuratorFrameworkFactory.newClient(connectionString, retryPolicy)
      curator.start()
      curator
    })
}
```

And I replaced the new curator creation / start in the makeBeam by : 
```
val curator = CuratorCache("tranquility", zkQuorum, new BoundedExponentialBackoffRetry(100, 3000, 5))
```

By doing that, I always get the same curator connection for every RDD in an executor, I see the log message "New curator <$curatorId:$connectionString>" only once per executor in my logs
And as a bonus, when the executor exits, the curator should close properly

What do you think of this approach?

**Comment by gianm** [comment]
@plelevier I think you're on the right track, though there are some other heavy per-beam objects (like connection pools to Druid) so I think a pool of Beams would work better than a pool of Curators. #115 updates the docs to reflect that.

About the shutdown hooks, I'm not totally sure that they will always do the right thing- I think Spark registers its own hooks and normally they all run simultaneously. So that might cause the curators to get closed before Spark finished (or even started) shutting down. Do you know if that's a problem?

**Comment by plelevier** [comment]
@gianm Great! I'll check your solution on monday

About shutdown hooks, I'm not sure too. On the other hand, not closing connections should be less an issue with 1 connection per executor. I'll check if I find something to handle that cleanly

**Comment by olegZastavnyi** [comment]
@plelevier have you solved the problem ? If yes could you please share you solution. 
Thanks

**Comment by plelevier** [comment]
Hi @olegZastavnyi ,
Yes we solved the problem. 
The tranquility documentation has been updated : https://github.com/druid-io/tranquility/blob/master/docs/spark.md

By using the pattern described on this page it should be ok (in short : instead of a lazy val, use a singleton object to handle the beam instance)

Please also note that you should use the 0.8.0 version since tranquility for spark 0.7.4 itself was suffering of the same kind of problems with tranquilizer threads (which was resulting in a memory leak)

**Comment by olegZastavnyi** [comment]
@plelevier Nice to hear that. 
I have one more problem. Druid stops receive any data when segment granularity ends. I am using Spark Streaming so I need to have like real time processing 24/7. Maybe you had some similar problem? 
Thanks

**Comment by plelevier** [comment]
@olegZastavnyi , we've never experienced this kind of problems. 

What's your beam configuration (DruidBeamConfig & ClusteredBeamTuning parameters)?

**Comment by olegZastavnyi** [comment]
I am using the same example: https://github.com/druid-io/tranquility/blob/master/docs/spark.md
class SimpleEventBeamFactory extends BeamFactory[SimpleEvent]
{
  def makeBeam: Beam[SimpleEvent] = SimpleEventBeamFactory.BeamInstance
}

object SimpleEventBeamFactory
{
  val BeamInstance: Beam[SimpleEvent] = {
    // Tranquility uses ZooKeeper (through Curator framework) for coordination.
    val curator = CuratorFrameworkFactory.newClient(
      "localhost:2181",
      new BoundedExponentialBackoffRetry(100, 3000, 5)
    )
    curator.start()

    val indexService = "druid/overlord" // Your overlord's druid.service, with slashes replaced by colons.
    val discoveryPath = "/druid/discovery"     // Your overlord's druid.discovery.curator.path
    val dataSource = "foo"
    val dimensions = IndexedSeq("bar")
    val aggregators = Seq(new LongSumAggregatorFactory("baz", "baz"))

    // Expects simpleEvent.timestamp to return a Joda DateTime object.
    DruidBeams
      .builder((simpleEvent: SimpleEvent) => simpleEvent.timestamp)
      .curator(curator)
      .discoveryPath(discoveryPath)
      .location(DruidLocation(indexService, dataSource))
      .rollup(DruidRollup(SpecificDruidDimensions(dimensions), aggregators, QueryGranularity.MINUTE))
      .tuning(
        ClusteredBeamTuning(
          segmentGranularity = Granularity.HOUR,
          windowPeriod = new Period("PT10M"),
          partitions = 1,
          replicants = 1
        )
      )
      .buildBeam()
  }
}

**Comment by plelevier** [comment]
On the DruidBeams builder there is a mthod druidBeamConfig which takes a DruidBeamConfig as a parameter, you can define some parameters with it if needed.

You should review your spark logs to see if something related to tranquility is happening.
If nothing special is found, review the druid logs.

Take also a look to your simpleEvent timestamps : 
if your tests are pushing events that have a timestamp older than 1 hour and 10 minutes they will be discarded (timestamp < now - segmentGranularity - windowPeriod), it can happen if you are making a simple loop to push always push the same event

**Comment by olegZastavnyi** [comment]
plelevier. Fixed. Window period was the issue.
