### ISSUE TITLE
Not able to compile tranquility source code

### ISSUE THREAD

**Issue by varmasaurav** [druid-io/tranquility#136]
I cloned the tranquility and tried to build with "sbt complile" but I keep getting the below error.

[info] Packaging /Users/saurav/quantiply/dev-env/tranquility/target/scala-2.10/root_2.10-0.7.4-SNAPSHOT.jar ...
[info] Done packaging.
[info] Compiling 1 Java source to /Users/saurav/quantiply/dev-env/tranquility/kafka/target/scala-2.10/classes...
**[error] /Users/saurav/quantiply/dev-env/tranquility/kafka/src/main/java/com/metamx/tranquility/kafka/writer/WriterController.java:58: error: cannot find symbol
[error]     this.dataSourceConfigList.sort(
[error]                              ^
[error]   symbol:   method sort(<anonymous Comparator<DataSourceConfig<PropertiesBasedKafkaConfig>>>)
[error]   location: variable dataSourceConfigList of type List<DataSourceConfig<PropertiesBasedKafkaConfig>>
[error] 1 error**
[warn] No main class detected
[warn] No main class detected
[warn] No main class detected
[warn] No main class detected

Following information may prove useful

Scala version - scala -version
Scala code runner version 2.11.7 -- Copyright 2002-2013, LAMP/EPFL

Sbt 
[info] server/*:sbtVersion
[info] 	0.13.7
[info] samza/*:sbtVersion
[info] 	0.13.7
[info] kafka/*:sbtVersion
[info] 	0.13.7
[info] spark/*:sbtVersion
[info] 	0.13.7
[info] flink/*:sbtVersion
[info] 	0.13.7
[info] core/*:sbtVersion
[info] 	0.13.7
[info] storm/*:sbtVersion
[info] 	0.13.7
[info] root/*:sbtVersion
[info] 	0.13.7

**Comment by gianm** [comment]
@varmasaurav, I'm not sure what's going on here as I cannot reproduce this.

Are you still seeing problems with the latest master? Could you try `sbt clean` or perhaps re-cloning from Github before building again?

**Comment by varmasaurav** [comment]
Thanks Gian. I found that Kafka uses a sort function thats present in Java 8. I bumped up my java installation from 7 to 1.8 and was able to compile.

**Comment by gianm** [comment]
Hey @varmasaurav, thanks for getting to the bottom of this. We're fixing that in #144.
