### ISSUE TITLE
Need to bump Curator version

### ISSUE THREAD

**Issue by ramkumarvenkat** [druid-io/tranquility#142]
I recently faced an issue when the curator connect string having multiple hosts (comma-separated) and there shouldn't be any spaces between the comma and the host. If it does, then we will have UnknownHostException, because the string isn't trimmed after splitting on the comma.

Looks like this was fixed long time back: https://issues.apache.org/jira/browse/ZOOKEEPER-1619. 

Can we please have the curator version bumped?

**Comment by gianm** [comment]
@ramkumarvenkat, that ZK version hasn't had a stable release yet (3.5.x has been in alpha for a LONG time!)

We will definitely update when it's stable.
