### ISSUE TITLE
[Feature] Auto fill discovery path from config file

### ISSUE THREAD

**Issue by du00cs** [druid-io/tranquility#150]
`druid.discovery.curator.path` is mentioned in the [properties part](https://github.com/druid-io/tranquility/blob/master/docs/configuration.md#properties), but actually it is not loaded. I don't know if there is any connection to #62 .

Currently, I have to add lines to manually set the discovery path.

```scala
val dataSource = getDataSource(file)

instance =
   DruidBeams.fromConfig(dataSource)
       .discoveryPath(dataSource.propertiesBasedConfig.discoPath)
       .buildBeam()
```

 I think it is nice to add it to `DruidBeams` and the function
```scala
  private def fromConfigInternal[InputType, MessageType](
    inputFnFn: (DruidRollup, TimestampSpec) => (InputType => MessageType),
    timestamperFn: TimestampSpec => Timestamper[MessageType],
    config: DataSourceConfig[_ <: PropertiesBasedConfig]
  ): Builder[InputType, MessageType]
```

Maybe just one line is needed.

**Comment by gianm** [comment]
Hey @du00cs, thanks for the catch. This'll be fixed by #151.
