### ISSUE TITLE
message dropped 

### ISSUE THREAD

**Issue by redlion99** [druid-io/tranquility#157]
The tranquility version I'm using is 0.8.3

All message is dropped, and I got the error message as below:

com.metamx.tranquility.tranquilizer.MessageDroppedException: null
	at com.twitter.finagle.NoStacktrace(Unknown Source) ~[na:na]

**Comment by redlion99** [comment]
I'm sure that the message timestamp is not outside the windowPeriod

Here is the task configuration:


"tuningConfig" : {
      "type" : "realtime",
      "maxRowsInMemory" : 75000,
      "intermediatePersistPeriod" : "PT10M",
      "windowPeriod" : "PT45M",
      "basePersistDirectory" : "/tmp/1461024041523-0",
      "versioningPolicy" : {
        "type" : "intervalStart"
      },
      "rejectionPolicy" : {
        "type" : "none"
      },
      "maxPendingPersists" : 0,
      "shardSpec" : {
        "type" : "linear",
        "partitionNum" : 2
      },
      "indexSpec" : {
        "bitmap" : {
          "type" : "concise"
        },
        "dimensionCompression" : null,
        "metricCompression" : null
      },
      "persistInHeap" : false,
      "ingestOffheap" : false,
      "aggregationBufferRatio" : 0.5,
      "bufferSize" : 134217728
    }



Here is the log of the dropped message:


10:23:16.131 [Hashed wheel timer #2] ERROR c.c.e.e.o.GeneralEventBeamFactory$$anonfun$local$1$$anon$1 - Dropped message: Map(rootDomain -> ospreypacks.com.cn, duration -> 0, city -> Sichuan Sheng, source -> 内部链接, path -> /cdkey/use/product_register, timestamp -> 2016-04-19T02:22:09Z, event -> session_stop_from, browser -> , domain -> www.ospreypacks.com.cn, isFirstTry -> false, os -> , targetId -> 3489808979, utmb -> 1557273461.80985290.1461030705.1461030705.1, triggerByCustomer -> false, pageId -> 3489808979, newSession -> 1, token -> 1557273461.80985290, subdivision -> Chengdu, targetName -> 新卡注册 | OspreyPacks, utma -> 1557273461.80985290.300518057.1461030705.1461030705.1, eventGroup -> session, tenantId -> 10, platform -> , refDomain -> www.ospreypacks.com.cn, hosting -> web, userCount -> 0)


Is there any way that I can know the reason of the message dropping?

**Comment by redlion99** [comment]
This is caused by by network issue with the task

**Comment by ayush15690** [comment]
How do you fix this ? Any idea??
