### ISSUE TITLE
[Spark Streaming] Background Send Thread Not Exit

### ISSUE THREAD

**Issue by du00cs** [druid-io/tranquility#158]
I use tranquility with spark streaming for some while and I find a big problem that will make it impossible to run long enough. A [Google Group thread](https://groups.google.com/forum/#!topic/druid-user/zJXLPpDLV70) has mentioned it in Feb. 

With the streaming job running, 
```bash
jstack 69069 | grep Tranquilizer-BackgroundSend- | wc -l
```
shows that growing number of threads in waiting.
```
// com.metamx.tranquility.tranquilizer.Tranquilizer: L101

val sendThread = loggingThread {
    try {
      while (!Thread.currentThread().isInterrupted) {
        val (exIndex, exBuffer) = lock.synchronized {
          while (
            buffer.isEmpty ||
              pendingBatches.size >= maxPendingBatches ||
              (!flushing && lingerMillis > 0 && System.currentTimeMillis() < bufferStartMillis + lingerMillis)
          ) {
            if (lingerMillis == 0 || bufferStartMillis == 0) {
              lock.wait() // here
```
More and more threads in memory will at last make the streaming job exceed the memory limit and killed by yarn.

The `stop` method of `Tranquilizer` can not be called at all, for it will make the sender in next stages sent nothing! 

My solution is rather simple, manually stop the sender thread. And after doing this, the daemon threads will not grow any more.

If you need some reproducible cases, I can attach them here. I will create a PR soon later.

**Comment by du00cs** [comment]
@fjy Debug for some while and I locate an issue with it. This will improve the stability and I will test the throughput later. Hope it works too.

**Comment by plelevier** [comment]
Need a fix for this too

**Comment by du00cs** [comment]
@plelevier Resolved in master. You can try it now
