### ISSUE TITLE
jetty-webapp dependency issues with Samza

### ISSUE THREAD

**Issue by gianm** [druid-io/tranquility#16]
See here: https://groups.google.com/forum/#!topic/druid-development/3Mh-7xqQOJs

**Comment by gianm** [comment]
I had worked around it by including this in my project's highest level pom:

    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-server</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-servlet</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-webapp</artifactId>
      <version>${jetty.version}</version>
    </dependency>

With the jetty version:

  <properties>
    <jetty.version>8.1.11.v20130520</jetty.version>
  </properties>

**Comment by gianm** [comment]
closing, we're using a different jetty now

**Comment by gabhishek** [comment]
Hi @gianm 

I am trying to use tranquility in my samza job. I added following dependency in my build.gradle :-

    compile group: 'io.druid', name: 'tranquility-samza_2.10', version: '0.8.2'

but I get following error when I run my job:-
![screen shot 2016-12-13 at 3 04 02 pm](https://cloud.githubusercontent.com/assets/12693622/21134805/7b05fc02-c145-11e6-9c92-876cd2eefb74.png)

Even the latest version of samza 0.11.0 is using jetty  8.1.8.v20121106 and it is conflicting with jetty version of tranquility.  I even tried using older versions if tranquility way back to 0.6.2. Could not find a solution.
