### ISSUE TITLE
Batch Example

### ISSUE THREAD

**Issue by giaosudau** [druid-io/tranquility#189]
I saw there was a Scala, Java example for Realtime ingestion but how about about the Batch one?

**Comment by nishantmonu51** [comment]
Tranquility is used for streaming ingestion of realtime data only. It is not used for Batch Ingestion.  
For Batch ingestion in druid refer to docs here - 
http://druid.io/docs/latest/ingestion/batch-ingestion.html

**Comment by giaosudau** [comment]
@nishantmonu51 
Why is Beam API mention in the document.

> Beam, a low-level API where you provide a batch of messages and get a future for that batch. You need to handle batching yourself.

https://github.com/druid-io/tranquility/blob/master/docs/core.md#beam-api
