### ISSUE TITLE
How to build a tranquility distribution

### ISSUE THREAD

**Issue by iAlaska** [druid-io/tranquility#191]
Hi, I am new to SBT. 
And now ,i want to build tranquility from source to generate a distribution Tarball.

I've execute `sbt +package` but i could not find the tar.gz file in the target directory.

thanks a lot!

**Comment by du00cs** [comment]
I just solved the problem today. `sbt 'project distribution' bundle:dist` , if it does not work, 

```bash
sbt
> compile
> project distribution
> bundle:dist
```

this should work.

**Comment by iAlaska** [comment]
Great thanks.  I found the solution in druid-usergoup yesterday.
```
sbt 'project distribution' universal:packageZipTarball
```
