### ISSUE TITLE
NoBrokersAvailableException

### ISSUE THREAD

**Issue by aakashvit** [druid-io/tranquility#208]
whet I am trying to insert sample data into druid using tranquility 
i m getting following error
com.twitter.finagle.NoBrokersAvailableException: No hosts are available for :home:aakash:Videos:Druid:druid-0.9.2:conf:druid:overlord, Dtab.base=[], Dtab.local=[]

**Comment by sharninder** [comment]
Is kafka working?

**Comment by Jin-Soul** [comment]
you can set the druid.host property in common.runtime.properties file ,
and restart druid server,have a try!

**Comment by aakashvit** [comment]
thanks for reply ,But I am not using Druid so I didn't tried after notice this issue.
