### ISSUE TITLE
0.9.0 Release Timeline

### ISSUE THREAD

**Issue by kevinconaway** [druid-io/tranquility#239]
@logarithm or @gianm are there any plans for the 0.9.0 release to be pushed to maven central?  The README seems to indicate that the artifacts are available but I think this is just in preparation for an actual release.

We've hit some artifact versioning conflicts in 0.8.2 that appear resolved in 0.9.0 so we're hoping that the release is available soon.

**Comment by ashwanilabs** [comment]
Will the upcoming release support Druid 0.10.0 features like numeric dimensions

**Comment by b-slim** [comment]
yes it does support numeric dimensions already (see http://druid.io/docs/latest/ingestion/schema-design.html#numeric-dimensions).

**Comment by ottomata** [comment]
@kevinconaway why closed?  I'm curious about this too:
> README seems to indicate that the artifacts are available

But I can't find them, or a v0.9.2 tag.

**Comment by kevinconaway** [comment]
@ottomata I moved this to the mailing list

https://groups.google.com/d/msgid/druid-user/CA%2B5XRVA3Q_codJ8chOY-KzzD%3DNqEjw4e%3Dztv%3DO_vm_wdih-4Hw%40mail.gmail.com?utm_medium=email&utm_source=footer
