### ISSUE TITLE
Realtime ingestion stop after some time

### ISSUE THREAD

**Issue by amoussoubaruch** [druid-io/tranquility#261]
Hi, 

I was using Druid since few month and try a realtime ingestion with tranquility spark scala API.
I used a kafka topic to take messages in real time (300 messages per second). 
I start my spark jar with hour Granularity. Ingestion start well and take something like 10 min for ingestion and nothing after. I don't have any data. I am using 2 hours for window period so i can explain why i have no data ingest in druid. 
I have always this metric 
`"metric":"ingest/events/processed","value":0`

I have druid cluster with 6 nodes : 2 overlord and 2 coordinator in same machine; middlemanager, brocker and historical are start on all of them. 

Whats is the best way to find if realtime ingestion work fine? 
How can i verify that if 200 messages come in window period i have the same message in druid in this period. 

Thanks

**Comment by mentholi** [comment]
Hi, I havent really used Tranquility myself and was just checking it out so I might not be the best person to answers this.. But have you checked that the process doesn't run out of memory if you publish 300 messages per second. I would try to produce only few hundred messages and setting the window period smaller so ypu wpuld probably see easier if ingestion is working. If so, then investigate if it runs out of memory or something.

**Comment by amoussoubaruch** [comment]
Hi @mentholi 

I found the problem. I done lot of data processing before storing to druid and i have a latency after a message push in druid and my application take time to update to new timestamp. 

Thanks
