### ISSUE TITLE
Segment don't close after segment granularity period

### ISSUE THREAD

**Issue by amoussoubaruch** [druid-io/tranquility#263]
Hi,

I was started a real time ingestion and i used 10 min for segmentGranularity. Most task create for each real time task don't close the segment. Since 12 hours i have now more than 20 tasks already running.
My comprehension is that after segmentGranularity period plus a window period segment for this time are being closed.
I don't understand why i have more tasks running since 12 hours.
Please, anyone have an idea?
Many thanks

**Comment by amrit-moengage** [comment]
Just check logs of Historical nodes, It can lead you to the cause of tasks still running.

**Comment by amoussoubaruch** [comment]
Hi @amrit-moengage 

Thanks for your answers. I solved this issue. It's related to local deep storage. If you have druid cluster, don't use local deep storage. Configure deep storage with hdfs or something like that.
