### ISSUE TITLE
Does tranquility 0.8.2 work with Druid 0.9.2?

### ISSUE THREAD

**Issue by noppanit** [druid-io/tranquility#264]
We're trying to upgrade Druid to 0.9.2 but as soon as we did that we don't see tasks getting created. We use it with Storm.

**Comment by noppanit** [comment]
I didn't get error or anything but the tasks aren't created in the index nodes.

**Comment by cheleb** [comment]
Tranquility core does work. Be aware of the time window issue ....

**Comment by noppanit** [comment]
Thanks!
