### ISSUE TITLE
Download link for 0.9.0 distribution broken

### ISSUE THREAD

**Issue by greg-v** [druid-io/tranquility#269]
The downloads section on the main README.md page (https://github.com/druid-io/tranquility/blob/master/README.md#downloadable-distribution) lists a link to download the latest distribution (0.9.0):

http://static.druid.io/tranquility/releases/tranquility-distribution-0.9.0.tgz

This link appears to be broken.

**Comment by chandresh-pancholi** [comment]
+1

**Comment by iwangheng** [comment]
+1

**Comment by gianm** [comment]
Should be fixed by #274. The correct link should be to 0.8.2 (the current version)
