### ISSUE TITLE
DataSchema constructor mismatch with druid 0.8.2

### ISSUE THREAD

**Issue by rasahner** [druid-io/tranquility#47]
just recording that I'm seeing this error when running tranquility with druid 0.9 jars:
  2015-11-04T23:00:50,557 ERROR [ClusteredBeam-ZkFuturePool-5998d9e6-6fc8-45c4-9769-163ed08247f7] com.metamx.tranquility.beam.ClusteredBeam - Failed to update cluster state: overlord/tranquility_test
java.lang.NoSuchMethodError: io.druid.segment.indexing.DataSchema.<init>(Ljava/lang/String;Lio/druid/data/input/impl/InputRowParser;[Lio/druid/query/aggregation/AggregatorFactory;Lio/druid/segment/indexing/granularity/GranularitySpec;)V
        at com.metamx.tranquility.druid.DruidBeamMaker.com$metamx$tranquility$druid$DruidBeamMaker$$taskObject(DruidBeamMaker.scala:84) ~[tranquility-core_2.11-0.6.2.jar:0.6.2]

This is doing "new DataSchema" with 4 arguments, but the DataSchema constructor has 5 arguments as of druid PR #1695, which I think is in druid 0.8.2.

**Comment by gianm** [comment]
the Druid Java APIs do have a way of changing constantly from version to version (even in a minor update since they're not considered public APIs). So Tranquility will generally only work with the exact version of Druid that it was built with, or maybe one very close.

Do you need to run with the newer jars for some reason?

**Comment by rasahner** [comment]
We have a tranquility test that I was trying to run from inside druid/integration-tests, with the idea that I'd contribute it to the community.  But I've been running into enough problems that it was easy to be convinced that a tranquility test isn't properly part of druid integration tests in any case, but would rather be part of a (nonexistent so far) integration test suite for tranquility.  We're currently running the test with druid 0.8 - we'll have to figure out something to do with it when we move to 0.8.2. 

If tranquility uses something that's not considered a public API, then maybe tranquility should be bundled in with druid, or maybe the something should become part of a public API.

(Another unrelated problem I was having had to do with the modules that are dependencies in the druid/integration-tests build - the mysql metadata one was causing guice initialization errors when tranquility tried to do injection, I think because something it depends on was being brought in by druid's Initialization.inject method, which is executed by testng for the tests but not by tranquility.)

**Comment by rasahner** [comment]
We have a tranquility test that I was trying to run from inside druid/integration-tests, with the idea that I'd contribute it to the community.  But I've been running into enough problems that it was easy to be convinced that a tranquility test isn't properly part of druid integration tests in any case, but would rather be part of a (nonexistent so far) integration test suite for tranquility.  We're currently running the test with druid 0.8 - we'll have to figure out something to do with it when we move to 0.8.2.  

If tranquility uses something that's not considered a public API, then maybe tranquility should be bundled in with druid, or maybe the something should become part of a public API.

(Another unrelated problem I was having had to do with the modules that are dependencies in the druid/integration-tests build - the mysql metadata one was causing guice initialization errors when tranquility tried to do injection, I think because something it depends on was being brought in by druid's Initialization.inject method, which is executed by testng for the tests but not by tranquility.) 
 


     On Thursday, November 5, 2015 5:26 PM, Gian Merlino <notifications@github.com> wrote:
   

 the Druid Java APIs do have a way of changing constantly from version to version (even in a minor update since they're not considered public APIs). So Tranquility will generally only work with the exact version of Druid that it was built with, or maybe one very close.Do you need to run with the newer jars for some reason?—

**Comment by gianm** [comment]
hmm, perhaps the best solution is to avoid the actual Druid objects and just speak its JSON API. The JSON API is supposed to be the public one.

**Comment by rasahner** [comment]
It seems to me that's the best solution.
 


    On Thursday, November 19, 2015 10:30 AM, Gian Merlino <notifications@github.com> wrote:
 

 hmm, perhaps the best solution is to avoid the actual Druid objects and just speak its JSON API. The JSON API is supposed to be the public one.—
