### ISSUE TITLE
Tranquility causes data loss due to re-use of finangle service name

### ISSUE THREAD

**Issue by rohitkochar** [druid-io/tranquility#53]
i have hit a bug where tranquility will cause data loss due to re-use of the service name of the finangle service ,for certain combination of segment granularity and window period.

Here are the details of my setup:
 Segment granularity:Minute
 Window period = 120 minutes
 datatsource name = ds1

In case of segment granularity is minute,tranquility picks only the minute part of the task interval along with the replicant number and partition number to form the name of the finangle service.

For an interval of [2015-11-19T07:00 - 2015-11-19T07:01] and for replicant number 0 and partition number 0 the service name would be "<firehose pattern>ds1-00-0000-0000" where firehose pattern is a static value.

Tranquility uses this service name to query the zoo keeper to  identify the <peon host> and <peon port> details where it can send data and in scenarios where same service name is used to connect to more than 1 firehose than it will get multiple destinations to for a service.

In the scenario given above same service name would be used to connect to task running at 7:00 and task running at 6:00 and since window period is 2 hours when a DruidBeam is constructed to post events to task of interval 7:00 it will get <host:port> details of two different peon since 6:00 task would still be alive.
If a finagle client is created with more than 1 destination then it starts sending data to them in round robin way in order to do load balancing hence causing half the data of 7:00 to go to task 6:00 which eventually drops it and hence data loss happens.

I have verified that in my setup i see no data loss in scenarios where window period is less than 60 minutes and segment granularity is minute whereas i see almost half data getting lost in the scenario explained above.

**Comment by gianm** [comment]
@rohitkochar, yes, this is a limitation of the way the service names get generated, when your windowPeriod is > your segmentGranularity. This is one of the reasons we recommend having windowPeriod < segmentGranularity (see the bottom of: http://druid.io/docs/latest/ingestion/realtime-ingestion.html).

I think you could work around this by modifying how the service names get generated, to have it cycle through a few more ids (maybe include hour mod 6?) before repeating the cycle. Do you think that sort of change would be helpful to you?

Long term the best solution is for the overlord to tell tranquility where it can find a task, so we don't need to use service discovery like this.

**Comment by rohitkochar** [comment]
What would be the side effects of using the entire interval range as part of the service name??
Is it that we will create too many Z nodes in zookeeper(one for each service) which won't get deleted?

Lets say i want the window period of 2 hours,than my segment granularity has to be DAY.
In that case how many realtime task would be launched per day?
Will be there be 1 task at the start of the day ,which will run for 2 hours and thereafter one more task will get launched?

**Comment by gianm** [comment]
@rohitkochar, sorry you were hit by this issue.

Could you help me understand why you are using segmentGranularity=minute with windowPeriod 120 minutes? That means you'd have 120 tasks running at once, which seems like quite a lot.

Anyway, yes, having too many service discovery znodes, that are never deleted, is the potential problem with unique service names. See the comment in DruidBeamMaker.generateBaseFirehoseId, which is the function that generates these ids. At one point we tried unique names + a Curator Reaper recipe, but the Reaper broke listeners for services that would go away and then come back.

A patch to fix this for your case (without having an unbounded number of service names) would be awesome. If you don't have time for that then we can use this issue to track the fix in general. I think in the short term, considering windowPeriod would be useful, and in the long term, tranquility should use an overlord API to get the host:port for a task.

**Comment by rohitkochar** [comment]
@gianm 
We round off the timestamp to nearest 15 minutes window before ingesting which makes sure that we have only 4 task per hour

I would definitely like to contribute the fix for it,i will try if we can use the window period while forming the service name.
My only worry with that approach is window period can change across tasks and hence even using window period won't solve the issue in all cases.

**Comment by rohitkochar** [comment]
@gianm 
On the different note,while i was debugging this issue,i can verify from the logs that events were being received by the firehose(though of the wrong task),but i couldn't figure out which part of Druid's code drop events if they are outside the interval of the task.
For me,none of the "events/processed or events/thrown or events/unparseable" were getting incremented for these events,so i was wondering at what point were these actually getting dropped.

**Comment by gianm** [comment]
@rohitkochar Ah, okay, that makes sense. And yeah- with tranquility it does windowPeriod dropping on its own end, and doesn't even send the data to Druid. That's because to send it to Druid it would have to create a task for the segment, which would be wasteful if the data is just gonna get dropped. You can figure out how many events are dropped by looking at the return value from Beam.propagate.

I think taking the windowPeriod into account would be better than what we're doing now. If we can also detect when we know there are going to be problems, and issue a warning or throw an exception, that'd be even better.

**Comment by rohitkochar** [comment]
@gianm sure,i will try to provide a PR with the fix which will use the window period while forming the service name.

Gianm, i understand that tranquility drops the data which is outside the window period but in the  scenario described as part of this issue,data was well within the window period hence tranquility was not dropping rather sending to a wrong indexing task.
We could confirm that data was reaching the event firehose of the wrong task but could not further figure out at what point druid task drops the data which is outside the interval.
Task do perform a check to make sure data is not below the lower bound of interval but i couldn't find any check for data being dropped because it was outside the upper bound.

**Comment by gianm** [comment]
@rohitkochar great, thank you!

And, sorry, what I meant is that tranquility actually drops data on the client side (inside the tranquility lib). That's why you don't see events/thrownAway metrics in Druid.

**Comment by rohitkochar** [comment]
@gianm 
I have raised a PR for the fix here 
https://github.com/druid-io/tranquility/pull/67
Please review the same and let me know the feedback

This doesn't incorporate the suggestion of warning the user when we get more than 1 host for the same service because i couldn't find the place in the tranquility code where we could check for multiple host condition.
For me it looks like, to issue the warning we need to change the "DiscoResolver" class.

**Comment by rohitkochar** [comment]
@gianm 
This is the modified pull request 
https://github.com/druid-io/tranquility/pull/72
I have described my thought process in the description of pull request.

Please review the same.

**Comment by gianm** [comment]
FWIW the real fix for this issue is setting `druidBeam.taskLocator = overlord`, which will work starting in Druid 0.9.1. At that point this cycleBucket stuff won't be needed. #171 is a temporary workaround for certain cases.

**Comment by gianm** [comment]
I believe this to be addressed in the short term by #171, and in the slightly less short term by `druidBeam.taskLocator = overlord` in druid 0.9.1. so, closing.
